Merge release-debian-22.04.0 into 22.04.x
centreon/centreon-widget-host-monitoring pull request #145
Opened 2022-07-13 21:08 UTC by tuntoja

Please pull these awesome changes in!

2022-07-18 07:17 UTC, jeremyjaouen requested changes

2022-07-18 07:17 UTC, jeremyjaouen commented on Jenkinsfile
> +        sh 'docker run -i --entrypoint "/src/centreon-widget-host-monitoring/ci/scripts/widget-deb-package.sh" -w "/src" -v "$PWD:/src" -e "DISTRIB=bullseye" -e "VERSION=$VERSION" -e "RELEASE=$RELEAS
```suggestion
        sh 'docker run -i --entrypoint "/src/centreon-widget-host-monitoring/ci/scripts/widget-deb-package.sh" -w "/src" -v "$PWD:/src" -e "DISTRIB=bullseye" -e "VERSION=$VERSION" -e "RELEASE=$RELEASE" registry.centreon.com/centreon-debian11-dependencies:22.10'
```
This shouldnt be 22.04 instead of 22.10 ?

2022-07-18 07:17 UTC, jeremyjaouen commented on ci/Jenkinsfile
> +                    sh 'docker build --no-cache . -f Dockerfile.widget-debian11-dependencies -t registry.centreon.com/centreon-widget-debian11-dependencies:22.10'
```suggestion
                    sh 'docker build --no-cache . -f Dockerfile.widget-debian11-dependencies -t registry.centreon.com/centreon-widget-debian11-dependencies:22.10'
```
this shouldn't be 22.04 instead of 22.10

2022-07-18 07:21 UTC, jeremyjaouen commented on ci/Jenkinsfile
> +/*
This file doesnt exist on other widgets

2022-07-19 07:14 UTC, tuntoja commented on ci/Jenkinsfile
> +/*
cc @lgcosta @zguennoune02 if you have an idea about this ?

2022-07-19 08:56 UTC, lgcosta commented on ci/Jenkinsfile
> +/*
This file is not needed as we can use a common image to build

2022-07-19 11:29 UTC, lgcosta approved these changes

2022-07-21 07:08 UTC, jeremyjaouen approved these changes

2022-07-21 07:09 UTC, merged